FROM node:15.5-alpine AS builder
COPY . ./tester-matching-app
WORKDIR /tester-matching-app
RUN npm i
RUN $(npm bin)/ng build --prod

FROM nginx:1.19.6-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /tester-matching-app/dist/tester-matching-app/ /usr/share/nginx/html
