version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
  client:
    build:
      context: ./frontend/tester-matching-app
      dockerfile: Dockerfile.client
    ports:
      - "4200:80"
